apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: pipeline
spec:
  selector:
    app: jenkins-server
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-entrypoint
  namespace: pipeline
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30888