apiVersion: v1
kind: Service
metadata:
  name: jenkins-entrypoint
  namespace: pipeline
spec:
  type: NodePort
  selector:
    app: jenkins-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30888